project 'DroidKaigi 2019.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DroidKaigi 2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DroidKaigi 2019
  pod 'MaterialComponents/Snackbar', '~> 74.0'
  pod 'SwiftLint'
  pod 'LicensePlist'
  pod 'XLPagerTabStrip'
  pod 'R.swift'

  target 'DroidKaigi 2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DroidKaigi 2019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
