# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'danger'
gem 'danger-junit'
gem 'danger-android_lint'
gem 'danger-apkstats'
gem 'danger-checkstyle_reports'
gem 'pry'