#!/usr/bin/env bash

set -eu

cd $(git rev-parse --show-toplevel)

danger_path="$PWD/scripts/danger"

export BUNDLE_PATH="$danger_path/vendor/bundle"
export BUNDLE_GEMFILE="$danger_path/Gemfile"

export MERGED_JUNIT_RESULT_FILE="$PWD/merged_junit.xml"

dirs="$(find . -path "*/build/test-results/*" -type d -name "*UnitTest"|xargs)" || :

if [[ -n "$dirs" ]]; then
  merge_junit_files -i "$dirs" -o "$MERGED_JUNIT_RESULT_FILE"
fi

bundle exec danger --dangerfile="$danger_path/Dangerfile.assertions" --danger_id='assertions' --remove-previous-comments
