#!/usr/bin/env bash

set -eu
set -o pipefail

sync_origin_master() {
    git remote add "$PROJECT_USERNAME" "git@github.com:$PROJECT_SLUG.git"
    git fetch "$PROJECT_USERNAME" master

    cat<<EOF
git merge --ff "$PROJECT_USERNAME/master"

or

git rebase "$PROJECT_USERNAME/master"
EOF
}

sync_origin_master