#!/usr/bin/env bash

set -eu
set -o pipefail

user_name="${CIRCLE_PROJECT_USERNAME:-DroidKaigi}"
repo_name="${CIRCLE_PROJECT_REPONAME:-conference-app-2019}"

sync_origin_master() {
    git remote add "$user_name" "git@github.com:$user_name/$repo_name.git"
    git fetch "$user_name" master

    cat<<EOF
git merge --ff "$user_name/master"

or

git rebase "$user_name/master"
EOF
}

sync_origin_master