#!/usr/bin/env bash

set -eu

# see bash.source for MERGED_JUNIT_RESULT_FILE

dirs="$(find . -path "*/build/test-results/*" -type d -name "*UnitTest"|xargs)" || :

if [[ -n "$dirs" ]]; then
  merge_junit_files -i "$dirs" -o "$MERGED_JUNIT_RESULT_FILE"
fi
